/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Machine = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'location' : IDL.Text,
  'machineType' : IDL.Text,
  'lastMaintenanceDate' : IDL.Opt(Time),
  'companyId' : IDL.Text,
});
export const Personnel = IDL.Record({
  'loginCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'inviteCode' : IDL.Text,
  'companyId' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'associatedCode' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Company = IDL.Record({
  'mode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'adminCode' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'status' : IDL.Text,
  'startDate' : IDL.Text,
  'endDate' : IDL.Text,
  'progress' : IDL.Nat,
  'createdAt' : Time,
});
export const MaintenanceRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'machineId' : IDL.Text,
  'machineName' : IDL.Text,
  'maintenanceType' : IDL.Text,
  'description' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'completedDate' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});
export const Supplier = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'contactPerson' : IDL.Text,
  'phone' : IDL.Text,
  'email' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});
export const SafetyIncident = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'title' : IDL.Text,
  'incidentType' : IDL.Text,
  'severity' : IDL.Text,
  'date' : IDL.Text,
  'location' : IDL.Text,
  'description' : IDL.Text,
  'reportedBy' : IDL.Text,
  'status' : IDL.Text,
  'actions' : IDL.Text,
  'createdAt' : Time,
});
export const BudgetItem = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'itemType' : IDL.Text,
  'plannedAmount' : IDL.Text,
  'actualAmount' : IDL.Text,
  'projectId' : IDL.Text,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
});

export const Shift = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'title' : IDL.Text,
  'shiftType' : IDL.Text,
  'date' : IDL.Text,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'assignedPersonnel' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const TrainingRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'title' : IDL.Text,
  'trainingType' : IDL.Text,
  'provider' : IDL.Text,
  'personnelName' : IDL.Text,
  'personnelCode' : IDL.Text,
  'startDate' : IDL.Text,
  'endDate' : IDL.Text,
  'expiryDate' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const QualityCheck = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'title' : IDL.Text,
  'checkType' : IDL.Text,
  'machineId' : IDL.Text,
  'machineName' : IDL.Text,
  'inspector' : IDL.Text,
  'checkDate' : IDL.Text,
  'status' : IDL.Text,
  'score' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const VisitorEntry = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'visitorName' : IDL.Text,
  'visitorType' : IDL.Text,
  'company' : IDL.Text,
  'purpose' : IDL.Text,
  'hostName' : IDL.Text,
  'entryDate' : IDL.Text,
  'entryTime' : IDL.Text,
  'exitTime' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const RiskRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'title' : IDL.Text,
  'category' : IDL.Text,
  'probability' : IDL.Text,
  'impact' : IDL.Text,
  'riskLevel' : IDL.Text,
  'description' : IDL.Text,
  'owner' : IDL.Text,
  'mitigationPlan' : IDL.Text,
  'status' : IDL.Text,
  'reviewDate' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const SupplyChainRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'itemName' : IDL.Text,
  'supplierName' : IDL.Text,
  'category' : IDL.Text,
  'orderedQuantity' : IDL.Text,
  'deliveredQuantity' : IDL.Text,
  'unit' : IDL.Text,
  'orderDate' : IDL.Text,
  'expectedDate' : IDL.Text,
  'deliveryDate' : IDL.Text,
  'leadTimeDays' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});



export const MaintenanceCalendarRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'title' : IDL.Text,
  'machineId' : IDL.Text,
  'machineName' : IDL.Text,
  'maintenanceType' : IDL.Text,
  'frequency' : IDL.Text,
  'nextDueDate' : IDL.Text,
  'lastDoneDate' : IDL.Text,
  'responsible' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const SupplierEvalRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'supplierName' : IDL.Text,
  'evaluationPeriod' : IDL.Text,
  'qualityScore' : IDL.Text,
  'deliveryScore' : IDL.Text,
  'priceScore' : IDL.Text,
  'serviceScore' : IDL.Text,
  'overallScore' : IDL.Text,
  'recommendation' : IDL.Text,
  'evaluatedBy' : IDL.Text,
  'evaluationDate' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});


export const CapacityRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'resourceName' : IDL.Text,
  'resourceType' : IDL.Text,
  'totalCapacity' : IDL.Text,
  'usedCapacity' : IDL.Text,
  'unit' : IDL.Text,
  'period' : IDL.Text,
  'responsible' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const CalibrationRecord = IDL.Record({
  'id' : IDL.Text,
  'companyId' : IDL.Text,
  'instrumentName' : IDL.Text,
  'serialNumber' : IDL.Text,
  'category' : IDL.Text,
  'lastCalibrationDate' : IDL.Text,
  'nextCalibrationDate' : IDL.Text,
  'calibrationInterval' : IDL.Text,
  'calibratedBy' : IDL.Text,
  'location' : IDL.Text,
  'certificateNo' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMachine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Machine],
      [],
    ),
  'addPersonnelToCompany' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Personnel],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Project],
      [],
    ),
  'addMaintenanceRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MaintenanceRecord],
      [],
    ),
  'addSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Supplier],
      [],
    ),
  'addSafetyIncident' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SafetyIncident],
      [],
    ),
  'addBudgetItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BudgetItem],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMachine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteMaintenanceRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteSupplier' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteSafetyIncident' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteBudgetItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyInfo' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'getCompanyPersonnel' : IDL.Func([IDL.Text], [IDL.Vec(Personnel)], ['query']),
  'getDashboardStats' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMachines' : IDL.Func([IDL.Text], [IDL.Vec(Machine)], ['query']),
  'getMachineById' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Machine)], ['query']),
  'getMaintenanceRecords' : IDL.Func([IDL.Text], [IDL.Vec(MaintenanceRecord)], ['query']),
  'getProjects' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'getSuppliers' : IDL.Func([IDL.Text], [IDL.Vec(Supplier)], ['query']),
  'getSafetyIncidents' : IDL.Func([IDL.Text], [IDL.Vec(SafetyIncident)], ['query']),
  'getBudgetItems' : IDL.Func([IDL.Text], [IDL.Vec(BudgetItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCompany' : IDL.Func([IDL.Text, IDL.Text], [Company], []),
  'removePersonnelFromCompany' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegisterPersonnel' : IDL.Func([IDL.Text], [Personnel], []),
  'updateMachine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Machine],
      [],
    ),
  'updateMachineStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Machine],
      [],
    ),
  'updateMaintenanceRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MaintenanceRecord],
      [],
    ),
  'updatePersonnelRole' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Personnel],
      [],
    ),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Project],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Supplier],
      [],
    ),
  'updateSafetyIncident' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SafetyIncident],
      [],
    ),
  'addShift' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Shift],
      [],
    ),
  'getShifts' : IDL.Func([IDL.Text], [IDL.Vec(Shift)], ['query']),
  'updateShift' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Shift],
      [],
    ),
  'deleteShift' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addTrainingRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [TrainingRecord],
      [],
    ),
  'getTrainingRecords' : IDL.Func([IDL.Text], [IDL.Vec(TrainingRecord)], ['query']),
  'updateTrainingRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [TrainingRecord],
      [],
    ),
  'deleteTrainingRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateBudgetItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BudgetItem],
      [],
    ),
  'addQualityCheck' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [QualityCheck],
      [],
    ),
  'getQualityChecks' : IDL.Func([IDL.Text], [IDL.Vec(QualityCheck)], ['query']),
  'updateQualityCheck' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [QualityCheck],
      [],
    ),
  'deleteQualityCheck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addVisitorEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [VisitorEntry],
      [],
    ),
  'getVisitorEntries' : IDL.Func([IDL.Text], [IDL.Vec(VisitorEntry)], ['query']),
  'updateVisitorEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [VisitorEntry],
      [],
    ),
  'deleteVisitorEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addRiskRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RiskRecord],
      [],
    ),
  'getRiskRecords' : IDL.Func([IDL.Text], [IDL.Vec(RiskRecord)], ['query']),
  'updateRiskRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RiskRecord],
      [],
    ),
  'deleteRiskRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addSupplyChainRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SupplyChainRecord],
      [],
    ),
  'getSupplyChainRecords' : IDL.Func([IDL.Text], [IDL.Vec(SupplyChainRecord)], ['query']),
  'updateSupplyChainRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SupplyChainRecord],
      [],
    ),
  'deleteSupplyChainRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addMaintenanceCalendarRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MaintenanceCalendarRecord],
      [],
    ),
  'getMaintenanceCalendarRecords' : IDL.Func([IDL.Text], [IDL.Vec(MaintenanceCalendarRecord)], ['query']),
  'updateMaintenanceCalendarRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MaintenanceCalendarRecord],
      [],
    ),
  'deleteMaintenanceCalendarRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addSupplierEvalRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SupplierEvalRecord],
      [],
    ),
  'getSupplierEvalRecords' : IDL.Func([IDL.Text], [IDL.Vec(SupplierEvalRecord)], ['query']),
  'updateSupplierEvalRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SupplierEvalRecord],
      [],
    ),
  'deleteSupplierEvalRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addCapacityRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CapacityRecord],
      [],
    ),
  'getCapacityRecords' : IDL.Func([IDL.Text], [IDL.Vec(CapacityRecord)], ['query']),
  'updateCapacityRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CapacityRecord],
      [],
    ),
  'deleteCapacityRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addCalibrationRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CalibrationRecord],
      [],
    ),
  'getCalibrationRecords' : IDL.Func([IDL.Text], [IDL.Vec(CalibrationRecord)], ['query']),
  'updateCalibrationRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CalibrationRecord],
      [],
    ),
  'deleteCalibrationRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Machine = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'location' : IDL.Text,
    'machineType' : IDL.Text,
    'lastMaintenanceDate' : IDL.Opt(Time),
    'companyId' : IDL.Text,
  });
  const Personnel = IDL.Record({
    'loginCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'inviteCode' : IDL.Text,
    'companyId' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'associatedCode' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Company = IDL.Record({
    'mode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'adminCode' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'status' : IDL.Text,
    'startDate' : IDL.Text,
    'endDate' : IDL.Text,
    'progress' : IDL.Nat,
    'createdAt' : Time,
  });
  const MaintenanceRecord = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'machineId' : IDL.Text,
    'machineName' : IDL.Text,
    'maintenanceType' : IDL.Text,
    'description' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'completedDate' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });
  const Supplier = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'contactPerson' : IDL.Text,
    'phone' : IDL.Text,
    'email' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });
  const SafetyIncident = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'title' : IDL.Text,
    'incidentType' : IDL.Text,
    'severity' : IDL.Text,
    'date' : IDL.Text,
    'location' : IDL.Text,
    'description' : IDL.Text,
    'reportedBy' : IDL.Text,
    'status' : IDL.Text,
    'actions' : IDL.Text,
    'createdAt' : Time,
  });
  const BudgetItem = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'itemType' : IDL.Text,
    'plannedAmount' : IDL.Text,
    'actualAmount' : IDL.Text,
    'projectId' : IDL.Text,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
  });
  const Shift = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'title' : IDL.Text,
    'shiftType' : IDL.Text,
    'date' : IDL.Text,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'assignedPersonnel' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });
  const TrainingRecord = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'title' : IDL.Text,
    'trainingType' : IDL.Text,
    'provider' : IDL.Text,
    'personnelName' : IDL.Text,
    'personnelCode' : IDL.Text,
    'startDate' : IDL.Text,
    'endDate' : IDL.Text,
    'expiryDate' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });
  const QualityCheck = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'title' : IDL.Text,
    'checkType' : IDL.Text,
    'machineId' : IDL.Text,
    'machineName' : IDL.Text,
    'inspector' : IDL.Text,
    'checkDate' : IDL.Text,
    'status' : IDL.Text,
    'score' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });
  const VisitorEntry = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'visitorName' : IDL.Text,
    'visitorType' : IDL.Text,
    'company' : IDL.Text,
    'purpose' : IDL.Text,
    'hostName' : IDL.Text,
    'entryDate' : IDL.Text,
    'entryTime' : IDL.Text,
    'exitTime' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });
  const CapacityRecord = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'resourceName' : IDL.Text,
    'resourceType' : IDL.Text,
    'totalCapacity' : IDL.Text,
    'usedCapacity' : IDL.Text,
    'unit' : IDL.Text,
    'period' : IDL.Text,
    'responsible' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });
  const CalibrationRecord = IDL.Record({
    'id' : IDL.Text,
    'companyId' : IDL.Text,
    'instrumentName' : IDL.Text,
    'serialNumber' : IDL.Text,
    'category' : IDL.Text,
    'lastCalibrationDate' : IDL.Text,
    'nextCalibrationDate' : IDL.Text,
    'calibrationInterval' : IDL.Text,
    'calibratedBy' : IDL.Text,
    'location' : IDL.Text,
    'certificateNo' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : Time,
  });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMachine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Machine],
        [],
      ),
    'addPersonnelToCompany' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Personnel],
        [],
      ),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Project],
        [],
      ),
    'addMaintenanceRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [MaintenanceRecord],
        [],
      ),
    'addSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Supplier],
        [],
      ),
    'addSafetyIncident' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SafetyIncident],
        [],
      ),
    'addBudgetItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BudgetItem],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMachine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteMaintenanceRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteSupplier' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteSafetyIncident' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteBudgetItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyInfo' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'getCompanyPersonnel' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Personnel)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMachines' : IDL.Func([IDL.Text], [IDL.Vec(Machine)], ['query']),
    'getMachineById' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Machine)], ['query']),
    'getMaintenanceRecords' : IDL.Func([IDL.Text], [IDL.Vec(MaintenanceRecord)], ['query']),
    'getProjects' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'getSuppliers' : IDL.Func([IDL.Text], [IDL.Vec(Supplier)], ['query']),
    'getSafetyIncidents' : IDL.Func([IDL.Text], [IDL.Vec(SafetyIncident)], ['query']),
    'getBudgetItems' : IDL.Func([IDL.Text], [IDL.Vec(BudgetItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCompany' : IDL.Func([IDL.Text, IDL.Text], [Company], []),
    'removePersonnelFromCompany' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegisterPersonnel' : IDL.Func([IDL.Text], [Personnel], []),
    'updateMachine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Machine],
        [],
      ),
    'updateMachineStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Machine],
        [],
      ),
    'updateMaintenanceRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [MaintenanceRecord],
        [],
      ),
    'updatePersonnelRole' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Personnel],
        [],
      ),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Project],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Supplier],
        [],
      ),
    'updateSafetyIncident' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SafetyIncident],
        [],
      ),
    'addShift' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Shift],
        [],
      ),
    'getShifts' : IDL.Func([IDL.Text], [IDL.Vec(Shift)], ['query']),
    'updateShift' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Shift],
        [],
      ),
    'deleteShift' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addTrainingRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [TrainingRecord],
        [],
      ),
    'getTrainingRecords' : IDL.Func([IDL.Text], [IDL.Vec(TrainingRecord)], ['query']),
    'updateTrainingRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [TrainingRecord],
        [],
      ),
    'deleteTrainingRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateBudgetItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BudgetItem],
        [],
      ),
    'addQualityCheck' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [QualityCheck],
        [],
      ),
    'getQualityChecks' : IDL.Func([IDL.Text], [IDL.Vec(QualityCheck)], ['query']),
    'updateQualityCheck' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [QualityCheck],
        [],
      ),
    'deleteQualityCheck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addVisitorEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [VisitorEntry],
        [],
      ),
    'getVisitorEntries' : IDL.Func([IDL.Text], [IDL.Vec(VisitorEntry)], ['query']),
    'updateVisitorEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [VisitorEntry],
        [],
      ),
    'deleteVisitorEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addCapacityRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CapacityRecord],
        [],
      ),
    'getCapacityRecords' : IDL.Func([IDL.Text], [IDL.Vec(CapacityRecord)], ['query']),
    'updateCapacityRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CapacityRecord],
        [],
      ),
    'deleteCapacityRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addCalibrationRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CalibrationRecord],
        [],
      ),
    'getCalibrationRecords' : IDL.Func([IDL.Text], [IDL.Vec(CalibrationRecord)], ['query']),
    'updateCalibrationRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CalibrationRecord],
        [],
      ),
    'deleteCalibrationRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
