/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Company {
  'mode' : string,
  'name' : string,
  'createdAt' : Time,
  'adminCode' : string,
}
export interface Machine {
  'status' : string,
  'name' : string,
  'createdAt' : Time,
  'serialNumber' : string,
  'notes' : string,
  'location' : string,
  'machineType' : string,
  'lastMaintenanceDate' : [] | [Time],
  'companyId' : string,
}
export interface Personnel {
  'loginCode' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : string,
  'isActive' : boolean,
  'inviteCode' : string,
  'companyId' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'associatedCode' : [] | [string],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };

export interface Shift {
  'id' : string,
  'companyId' : string,
  'title' : string,
  'shiftType' : string,
  'date' : string,
  'startTime' : string,
  'endTime' : string,
  'assignedPersonnel' : string,
  'status' : string,
  'notes' : string,
  'createdAt' : Time,
}

export interface TrainingRecord {
  'id' : string,
  'companyId' : string,
  'title' : string,
  'trainingType' : string,
  'provider' : string,
  'personnelName' : string,
  'personnelCode' : string,
  'startDate' : string,
  'endDate' : string,
  'expiryDate' : string,
  'status' : string,
  'notes' : string,
  'createdAt' : Time,
}

export interface QualityCheck {
  'id' : string,
  'companyId' : string,
  'title' : string,
  'checkType' : string,
  'machineId' : string,
  'machineName' : string,
  'inspector' : string,
  'checkDate' : string,
  'status' : string,
  'score' : string,
  'notes' : string,
  'createdAt' : Time,
}

export interface VisitorEntry {
  'id' : string,
  'companyId' : string,
  'visitorName' : string,
  'visitorType' : string,
  'company' : string,
  'purpose' : string,
  'hostName' : string,
  'entryDate' : string,
  'entryTime' : string,
  'exitTime' : string,
  'status' : string,
  'notes' : string,
  'createdAt' : Time,
}


export interface PermissionRole {
  'id': string,
  'companyId': string,
  'name': string,
  'modules': Array<string>,
  'createdAt': Time,
}

export interface PersonnelPermission {
  'loginCode': string,
  'companyId': string,
  'roleId': string,
  'additionalModules': Array<string>,
  'removedModules': Array<string>,
}

export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMachine' : ActorMethod<
    [string, string, string, string, string, string],
    Machine
  >,
  'addPersonnelToCompany' : ActorMethod<[string, string, string], Personnel>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMachine' : ActorMethod<[string, string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyInfo' : ActorMethod<[string], [] | [Company]>,
  'getCompanyPersonnel' : ActorMethod<[string], Array<Personnel>>,
  'getDashboardStats' : ActorMethod<[string], string>,
  'getMachines' : ActorMethod<[string], Array<Machine>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCompany' : ActorMethod<[string, string], Company>,
  'removePersonnelFromCompany' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegisterPersonnel' : ActorMethod<[string], Personnel>,
  'updateMachine' : ActorMethod<
    [string, string, string, string, string, string, string],
    Machine
  >,
  'updateMachineStatus' : ActorMethod<[string, string, string], Machine>,
  'updatePersonnelRole' : ActorMethod<[string, string, string], Personnel>,
  'addPermissionRole': ActorMethod<[string, string, Array<string>], PermissionRole>,
  'updatePermissionRole': ActorMethod<[string, string, string, Array<string>], PermissionRole>,
  'deletePermissionRole': ActorMethod<[string, string], boolean>,
  'getPermissionRoles': ActorMethod<[string], Array<PermissionRole>>,
  'setPersonnelPermission': ActorMethod<[string, string, string, Array<string>, Array<string>], PersonnelPermission>,
  'getPersonnelPermission': ActorMethod<[string, string], [] | [PersonnelPermission]>,
  'getMyAllowedModules': ActorMethod<[string], [] | [Array<string>]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
