/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Machine {
    status: string;
    name: string;
    createdAt: Time;
    serialNumber: string;
    notes: string;
    location: string;
    machineType: string;
    lastMaintenanceDate?: Time;
    companyId: string;
}
export interface Company {
    mode: string;
    name: string;
    createdAt: Time;
    adminCode: string;
}
export type Time = bigint;
export interface UserProfile {
    associatedCode?: string;
    name: string;
}
export interface Personnel {
    loginCode: string;
    name: string;
    createdAt: Time;
    role: string;
    isActive: boolean;
    inviteCode: string;
    companyId?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMachine(adminCode: string, name: string, machineType: string, serialNumber: string, location: string, notes: string): Promise<Machine>;
    addPersonnelToCompany(adminCode: string, inviteCode: string, role: string): Promise<Personnel>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteMachine(adminCode: string, machineId: string): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyInfo(userCode: string): Promise<Company | null>;
    getCompanyPersonnel(adminCode: string): Promise<Array<Personnel>>;
    getDashboardStats(userCode: string): Promise<string>;
    getMachines(userCode: string): Promise<Array<Machine>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerCompany(name: string, mode: string): Promise<Company>;
    removePersonnelFromCompany(adminCode: string, personnelId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selfRegisterPersonnel(name: string): Promise<Personnel>;
    updateMachine(adminCode: string, machineId: string, name: string, machineType: string, serialNumber: string, location: string, notes: string): Promise<Machine>;
    updateMachineStatus(userCode: string, machineId: string, status: string): Promise<Machine>;
    updatePersonnelRole(adminCode: string, personnelId: string, role: string): Promise<Personnel>;
}
import type { Company as _Company, Machine as _Machine, Personnel as _Personnel, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMachine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Machine> {
        if (this.processError) {
            try {
                const result = await this.actor.addMachine(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Machine_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMachine(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Machine_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPersonnelToCompany(arg0: string, arg1: string, arg2: string): Promise<Personnel> {
        if (this.processError) {
            try {
                const result = await this.actor.addPersonnelToCompany(arg0, arg1, arg2);
                return from_candid_Personnel_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPersonnelToCompany(arg0, arg1, arg2);
            return from_candid_Personnel_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteMachine(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMachine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMachine(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyInfo(arg0: string): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyInfo(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyInfo(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyPersonnel(arg0: string): Promise<Array<Personnel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyPersonnel(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyPersonnel(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getMachines(arg0: string): Promise<Array<Machine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMachines(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMachines(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerCompany(arg0: string, arg1: string): Promise<Company> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCompany(arg0, arg1);
            return result;
        }
    }
    async removePersonnelFromCompany(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removePersonnelFromCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePersonnelFromCompany(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async selfRegisterPersonnel(arg0: string): Promise<Personnel> {
        if (this.processError) {
            try {
                const result = await this.actor.selfRegisterPersonnel(arg0);
                return from_candid_Personnel_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfRegisterPersonnel(arg0);
            return from_candid_Personnel_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMachine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<Machine> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMachine(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Machine_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMachine(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Machine_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMachineStatus(arg0: string, arg1: string, arg2: string): Promise<Machine> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMachineStatus(arg0, arg1, arg2);
                return from_candid_Machine_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMachineStatus(arg0, arg1, arg2);
            return from_candid_Machine_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePersonnelRole(arg0: string, arg1: string, arg2: string): Promise<Personnel> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePersonnelRole(arg0, arg1, arg2);
                return from_candid_Personnel_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePersonnelRole(arg0, arg1, arg2);
            return from_candid_Personnel_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    // RBAC Methods
    async addPermissionRole(adminCode: string, roleName: string, modules: string[]): Promise<any> {
        return this.actor.addPermissionRole(adminCode, roleName, modules);
    }
    async updatePermissionRole(adminCode: string, roleId: string, roleName: string, modules: string[]): Promise<any> {
        return this.actor.updatePermissionRole(adminCode, roleId, roleName, modules);
    }
    async deletePermissionRole(adminCode: string, roleId: string): Promise<boolean> {
        return this.actor.deletePermissionRole(adminCode, roleId);
    }
    async getPermissionRoles(adminCode: string): Promise<any[]> {
        return this.actor.getPermissionRoles(adminCode);
    }
    async setPersonnelPermission(adminCode: string, loginCode: string, roleId: string, customTitle: string, additionalModules: string[], removedModules: string[]): Promise<any> {
        return this.actor.setPersonnelPermission(adminCode, loginCode, roleId, customTitle, additionalModules, removedModules);
    }
    async getPersonnelPermission(adminCode: string, loginCode: string): Promise<any> {
        const result = await this.actor.getPersonnelPermission(adminCode, loginCode);
        return result.length > 0 ? result[0] : null;
    }
    async registerCompanyAtomic(arg0: string, arg1: string): Promise<any> {
        return this.actor.registerCompanyAtomic(arg0, arg1);
    }
    async registerPersonnelAtomic(arg0: string): Promise<any> {
        return this.actor.registerPersonnelAtomic(arg0);
    }
}
function from_candid_Machine_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Machine): Machine {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Personnel_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Personnel): Personnel {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Company]): Company | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    associatedCode: [] | [string];
    name: string;
}): {
    associatedCode?: string;
    name: string;
} {
    return {
        associatedCode: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.associatedCode)),
        name: value.name
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    name: string;
    createdAt: _Time;
    serialNumber: string;
    notes: string;
    location: string;
    machineType: string;
    lastMaintenanceDate: [] | [_Time];
    companyId: string;
}): {
    status: string;
    name: string;
    createdAt: Time;
    serialNumber: string;
    notes: string;
    location: string;
    machineType: string;
    lastMaintenanceDate?: Time;
    companyId: string;
} {
    return {
        status: value.status,
        name: value.name,
        createdAt: value.createdAt,
        serialNumber: value.serialNumber,
        notes: value.notes,
        location: value.location,
        machineType: value.machineType,
        lastMaintenanceDate: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.lastMaintenanceDate)),
        companyId: value.companyId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loginCode: string;
    name: string;
    createdAt: _Time;
    role: string;
    isActive: boolean;
    inviteCode: string;
    companyId: [] | [string];
}): {
    loginCode: string;
    name: string;
    createdAt: Time;
    role: string;
    isActive: boolean;
    inviteCode: string;
    companyId?: string;
} {
    return {
        loginCode: value.loginCode,
        name: value.name,
        createdAt: value.createdAt,
        role: value.role,
        isActive: value.isActive,
        inviteCode: value.inviteCode,
        companyId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.companyId))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Personnel>): Array<Personnel> {
    return value.map((x)=>from_candid_Personnel_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Machine>): Array<Machine> {
    return value.map((x)=>from_candid_Machine_n1(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    associatedCode?: string;
    name: string;
}): {
    associatedCode: [] | [string];
    name: string;
} {
    return {
        associatedCode: value.associatedCode ? candid_some(value.associatedCode) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
